# Project information
site_name: BNBChain Knowledge Base
site_url: https://www.bnbchain.org
site_author: BNB Chain
site_description: >-
  Write your documentation in Markdown and create a professional static site in
  minutes – searchable, customizable for all devices
# Repository
repo_name: bnbchain
repo_url: https://github.com/bnb-chain/

markdown_extensions:
  - md_in_html
plugins:
  - offline
  - search
  # Page tree
nav:
  - Home: index.md
  - Annoucements: ./announce/index.md
  - BNB Smart Chain:
    - Overview: ./bnb_smart_chain/index.md
  - BNB opBNB:
    - Introduction: ./bnb_opbnb/index.md
    - Core Concepts:
      - Why BSC Requires opBNB: ./bnb_opbnb/core-concepts/why-bsc-requires-opbnb.md
      - Why OP Stack: ./bnb_opbnb/core-concepts/why-opstack.md
      - Optimizations on OP Stack: ./bnb_opbnb/core-concepts/optimisations-on-opstack.md
      - Metrics: ./bnb_opbnb/core-concepts/opbnb-metrics.md
      - Protocol Addresses: ./bnb_opbnb/core-concepts/opbnb-protocol-addresses.md
      - BNBChain Rollup as Service: ./bnb_opbnb/core-concepts/raas.md

theme:
  name: material
  logo: assets/bnb.svg
  favicon: assets/bnb.svg
  features:
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: white
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
- stylesheets/extra.css

extra:
  homepage: https://bnbchain.org
  alternate:
    - name: English
      link: /
      lang: en

# Copyright
copyright: Copyright &copy; 2024 BNB Chain

