# Project information
site_name: BNBChain Knowledge Base
site_url: https://www.bnbchain.org
site_author: BNB Chain
site_description: >-
  Write your documentation in Markdown and create a professional static site in
  minutes – searchable, customizable for all devices
# Repository
repo_name: bnbchain
repo_url: https://github.com/bnb-chain/

markdown_extensions:
  - md_in_html
plugins:
  - offline
  - search
# Page tree
nav:
  - Home: index.md
  - Announcements: ./announce/index.md
  - BNB Beacon Chain Fusion:
    - Overview: ./bc_fusion/index.md
    - For Users:
      - Manage Your Assets: ./bc_fusion/users/assets.md
      - Manage Your Atomic Swaps: ./bc_fusion/users/swaps.md
      - Manage Your TimeLocks: ./bc_fusion/users/timelocks.md
      - Manage Your Old Delegations: ./bc_fusion/users/stake-migration.md
      - BEP153 and LSD Stake Migration: ./bc_fusion/users/bep153-stake-migration.md
      - Manage Your New Delegations: ./bc_fusion/users/new-stake.md
      - Participate in Governance: ./bc_fusion/users/gov.md
    - For Token Issuers:
      - Bind Your Tokens: ./bc_fusion/owners/bind.md
    - For Validators:
      - Create New Validators: ./bc_fusion/validators/creation.md
      - Migrate Your Validators: ./bc_fusion/validators/migrations.md
      - Key Management: ./bc_fusion/validators/key-management.md
    - For Developers:
      - New Staking: ./bc_fusion/developers/staking.md
      - New Governance: ./bc_fusion/developers/gov.md
      - Cross Chain Redelegation: ./bc_fusion/developers/crosschain-redelegation.md
      - Build-in System Contracts: ./bc_fusion/developers/system-contracts.md
    - Native Staking & Governance:
      - Staking: ./bc_fusion/validators/staking.md
      - Slash: ./bc_fusion/validators/slash.md
      - Governance: ./bc_fusion/validators/gov.md
  - BNB Smart Chain:
    - Overview: ./bnb_smart_chain/index.md
    - Staking:
        - Overview: ./bnb_smart_chain/staking/index.md
        - User Guide: ./bnb_smart_chain/staking/user-guide.md
        - Developer Guide: ./bnb_smart_chain/staking/developer-guide.md
    - Governance:
        - Overview: ./bnb_smart_chain/governance/index.md
        - User Guide: ./bnb_smart_chain/governance/user-guide.md
        - Developer Guide: ./bnb_smart_chain/governance/developer-guide.md
    - Validator:
        - Overview: ./bnb_smart_chain/validator/index.md
        - Run Validator: ./bnb_smart_chain/validator/run-val.md
        - Create Validator: ./bnb_smart_chain/validator/create-val.md
        - Secure Validator: ./bnb_smart_chain/validator/security.md
        - Key Management: ./bnb_smart_chain/validator/manage-keys.md
        - MEV:
            - Overview: ./bnb_smart_chain/validator/mev/index.md
            - Validator Guide: ./bnb_smart_chain/validator/mev/validator-integration.md
            - Builder Guide: ./bnb_smart_chain/validator/mev/builder-integration.md
            - FAQs: ./bnb_smart_chain/validator/mev/faqs.md
    - Slashing:
        - Overview: ./bnb_smart_chain/slashing/index.md
        - Slash Events: ./bnb_smart_chain/slashing/slash-events.md
        - Unjail Validator: ./bnb_smart_chain/slashing/unjail.md
        - Monitor Slashing: ./bnb_smart_chain/slashing/monitor.md
  - BNB opBNB:
    - Introduction: ./bnb_opbnb/index.md
    - Core Concepts:
      - Why BSC Requires opBNB: ./bnb_opbnb/core-concepts/why-bsc-requires-opbnb.md
      - Why OP Stack: ./bnb_opbnb/core-concepts/why-opstack.md
      - Optimizations on OP Stack: ./bnb_opbnb/core-concepts/optimisations-on-opstack.md
      - Metrics: ./bnb_opbnb/core-concepts/opbnb-metrics.md
      - Protocol Addresses: ./bnb_opbnb/core-concepts/opbnb-protocol-addresses.md
      - BNBChain Rollup as Service: ./bnb_opbnb/core-concepts/raas.md
    - Get Started:
      - Network Information: ./bnb_opbnb/get-started/network-info.md
      - Wallet Configuration: ./bnb_opbnb/get-started/wallet-configuration.md
      - Deposit to opBNB: ./bnb_opbnb/get-started/deposit-to-opbnb.md
      - Withdraw from opBNB: ./bnb_opbnb/get-started/withdraw-from-opbnb.md
    - Developers:
      - Developer Tools: ./bnb_opbnb/developers/developer-tools.md
      - Network Faucet: ./bnb_opbnb/developers/network-faucet.md
      - Wallet Gas Price Setting: ./bnb_opbnb/developers/set-gas-price.md
      - Multi-sig Wallet: ./bnb_opbnb/developers/multisig-wallet.md
      - BEP20 CrossChain Introduction: ./bnb_opbnb/developers/bep20-crosschain.md
      - Geth P2P Sync Feature: ./bnb_opbnb/developers/geth-sync.md
      - Developers Cheat Sheet: ./bnb_opbnb/developers/cheat-sheet.md
    - Advanced Topics:
      - Local Development: ./bnb_opbnb/advanced/local-dev-env.md
      - Build a Full Stack dApp on opBNB: ./bnb_opbnb/advanced/full-stack-dapp.md
      - Verify Smart Contract on opBNBScan explorer: ./bnb_opbnb/advanced/verify-on-opbnbscan.md
      - Node Best Practices: ./bnb_opbnb/advanced/node-best-practices.md
      - Local Node: ./bnb_opbnb/advanced/local-node.md
      - Run with PebbleDB and PBSS: ./bnb_opbnb/advanced/run-with-pebbledb-and-pbss.md

theme:
  name: material
  logo: assets/bnb.svg
  favicon: assets/bnb.svg
  features:
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: white
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
- stylesheets/extra.css

extra:
  homepage: https://bnbchain.org
  alternate:
    - name: English
      link: /
      lang: en

# Copyright
copyright: Copyright &copy; 2024 BNB Chain

